### DISCUSSION TITLE
TB -> DF gRPC 호출 시, DF endpoint 설정 방법 관련

### DISCUSSION THREAD

**Discussion by jihoon-seo** [cloud-barista/cb-tumblebug#671] [General]
@powerkimhub @jmleefree 한번 검토 부탁드립니다 😊

[현황: TB -> SP gRPC 호출 시, DF endpoint 설정 방법]

1. `cb-tumblebug/conf/grpc_conf.yaml` 에 다음과 같이 기재되어 있습니다.

```yaml
version: 1
grpc:
  spidercli:
    server_addr: 127.0.0.1:2048
    timeout: 90s
    #tls:
    #  tls_ca: $CBTUMBLEBUG_ROOT/certs/ca.crt
    interceptors:
      #auth_jwt:
      #  jwt_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRJUCI6IjEyNy4wLjAuMSIsImV4cGlyZSI6MTkwODMyNTY1OCwib3JnTmFtZSI6IkVUUkkiLCJ1c2VyTmFtZSI6IkhvbmdHaWxEb25nIn0.4lkjYduo8iwv4AcKH96MpTnk8d7HRhi_p1xlnvZts8A
      opentracing:
        jaeger:
          endpoint: localhost:6832
          service_name: spider grpc client for tumblebug
          sample_rate: 1
```

즉, `cb-tumblebug/conf/grpc_conf.yaml` 에 `grpc.spidercli.server_addr: 127.0.0.1:2048` 이라고 기재합니다.

2. CB-TB에서 `err := ccm.SetConfigPath(os.Getenv("CBTUMBLEBUG_ROOT") + "/conf/grpc_conf.yaml")` 와 같이 호출하는데,
  이 `SetConfigPath` 함수는
  `cb-spider/interface/api/ccm.go` 에 `func (ccm *CCMApi) SetConfigPath(configFile string) error` 함수가,
  `cb-spider/interface/api/cim.go` 에 `func (cim *CIMApi) SetConfigPath(configFile string) error` 함수가 정의되어 있습니다.
  즉, `cb-tumblebug/conf/grpc_conf.yaml`에 기재된 내용이
  "CB-TB 바이너리 내의 CB-SP gRPC 클라이언트 부분"에 적용됩니다.

---

[DF 현황]
https://github.com/cloud-barista/cb-dragonfly/pull/110 를 살펴 보면,

1. `cb-dragonfly/pkg/config/grpc.go` 에 `func loadGrpcConfigFromYAML(config *GrpcConfig)` 가 있는데,
이는 "DF 바이너리 내의 DF gRPC 서버"가 listen할 IP주소와 포트를 설정하는 함수입니다.
"CB-TB 바이너리 내의 CB-DF gRPC 클라이언트 부분"과는 관계가 없습니다.

2. `cb-dragonfly/pkg/api/grpc/request/`에는
위의 2번에서 소개한 `SetConfigPath` 와 같은 함수는 없는 것으로 보입니다.

3. 대신, `cb-dragonfly/pkg/api/grpc/request/monitoring_api.go` 에
`func (monApi *MonitoringAPI) SetServerAddr(addr string) error` 함수는 있습니다.

이를 CB-TB 에서 사용한다면 다음과 같을 것입니다.

[As-is]
https://github.com/cloud-barista/cb-tumblebug/blob/a24db8327de434e4e958529de3e530fa8ebb3dec/src/core/mcis/monitor.go#L111-L112

[To-be]
```Go
		monApi := df_api.InitMonitoringAPI()
		err := monApi.SetServerAddr(<cb-tumblebug/conf/grpc_conf.yaml 에서 읽은 값>)
		err = monApi.Open()
```

---

[요약]
1. CB-Spider, CB-Tumblebug의 gRPC request (client) 관련 코드에는 
`grpc_conf.yaml` 파일을 읽고 처리하는 부분이 있음.
예를 들어, `cb-tumblebug/conf/grpc_conf.yaml` 에 SP gRPC 클라이언트 환경설정 사항을 적어 놓고,
CB-TB 바이너리를 실행하면, "CB-TB 코드에서 import하여 사용한 CB-SP gRPC 클라이언트 코드"에서
`cb-tumblebug/conf/grpc_conf.yaml`를 처리함

2. CB-Dragonfly의 gRPC request (client) 관련 코드에는 그러한 부분이 없음.

---

[안]
1. DF의 gRPC 클라이언트 코드도 SP, TB의 그것과 비슷하게 구성한다. 
(-> SP, TB와의 일관성이 좋아집니다.)
2. TB 코드에서 `cb-tumblebug/conf/grpc_conf.yaml` 안의 값을 읽고,
`monApi.SetServerAddr()`를 호출한다.
(-> SP, TB와의 일관성은 다소 떨어지게 됩니다.)
