### ISSUE TITLE
컨피그레이션 포멧 및 활용 방식 개선

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-tumblebug#1562]

**Comment by sykim-etri** [comment]
@seokho-son 
쿠버네티스 클러스터 프로비저닝을 위한 설정 파일 예시를 대략 다음과 같이 설계해 보았습니다. (작성된 값은 단순 참고용)
차후 추가되거나 변경될 항목들이 더 있을 수 있습니다만 cloudinfo.yaml과는 스타일이 조금 달라서 검토를 요청 드립니다.

아래 각 항목들의 대략적인 내용은 [구글시트](https://docs.google.com/spreadsheets/d/1mPmfnfmyszYimVzplZMzsqO3WsBmOdes/edit#gid=1299745060)를 참고하시면 됩니다.

``` yaml
clusterInfo:
  nhncloud:
    nodegroupsWithCluster: true
    nodeImage:
      - region: [kr1,kr2,kr3]
        configurable: true
        available:
          - default
          - aliyun_3_9_x64_20G_alibase_20231219.vhd
      - region: [jp1]
        configurable: false
   rootDisk:
      type:
        configurable: true
        available:
          - default
          - CLOUD_BASIC
      size:
        configurable: true
        min: 10
        max: 40
```
