### ISSUE TITLE
Suggestion: Ignore some files and directories in a workflow

### ISSUE THREAD

**Issue by hermitkim1** [cloud-barista/cb-tumblebug#356]
### [Suggestion]
Add `paths-ignore` to ignore some files and directories for executing the `build-and-publish-container-image.yaml` workflow efficiently

Currently, the workflow is performed frequently.

TO-BE (Commented are removed for readability)
```yaml
name: Build and publish container image

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '.all-contributorsrc'
      - '.gitignore'
      - 'LICENSE'
      - 'assets/**'
      - 'test/**'

  push:
    branches: master
    tags:
      - "v*.*.*"
    paths-ignore:
      - '**.md'
      - '.all-contributorsrc'
      - '.gitignore'
      - 'LICENSE'
      - 'assets/**'
      - 'test/**'
```

### [Need help]
Could you review the below and tell me any files or directories that need to be added or deleted?
```yaml
    paths-ignore:
      - '**.md'
      - '.all-contributorsrc'
      - '.gitignore'
      - 'LICENSE'
      - 'assets/**'
      - 'test/**'
```
